In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./iot_telemetry_data.csv')
df.head()

,ts,device,co,humidity,light,lpg,motion,smoke,temp
0,1.594512e+09,b8:27:eb:bf:9d:51,0.004956,51.000000,False,0.007651,False,0.020411,22.700000
1,1.594512e+09,00:0f:00:70:91:0a,0.002840,76.000000,False,0.005114,False,0.013275,19.700001
2,1.594512e+09,b8:27:eb:bf:9d:51,0.004976,50.900000,False,0.007673,False,0.020475,22.600000
3,1.594512e+09,1c:bf:ce:15:ec:4d,0.004403,76.800003,True,0.007023,False,0.018628,27.000000
4,1.594512e+09,b8:27:eb:bf:9d:51,0.004967,50.900000,False,0.007664,False,0.020448,22.600000

In [5]:
device2 = df[df['device']=='00:0f:00:70:91:0a']
del device2['device']
device2.head()

,ts,co,humidity,light,lpg,motion,smoke,temp
1,1.594512e+09,0.002840,76.000000,False,0.005114,False,0.013275,19.700001
7,1.594512e+09,0.002938,76.000000,False,0.005241,False,0.013628,19.700001
15,1.594512e+09,0.002905,75.800003,False,0.005199,False,0.013509,19.700001
20,1.594512e+09,0.002938,75.800003,False,0.005241,False,0.013628,19.700001
23,1.594512e+09,0.002840,76.000000,False,0.005114,False,0.013275,19.700001

In [6]:
device2[1:].to_csv('./device-2.csv', index=0)